// Auto-generated by tools/generate_blake_kit.py — edit kit definition, then re-run.
using System.Linq;
using BaseLib.Utils;
using Blake.BlakeCode;
using Blake.BlakeCode.Powers;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;

namespace Blake.BlakeCode.Cards.Common;

public sealed class DashAttack() : BlakeCard(0, CardType.Attack, CardRarity.Common, TargetType.AnyEnemy)
{
    protected override IEnumerable<DynamicVar> CanonicalVars =>
    [
        new DamageVar(3, ValueProp.Move),
        new DamageVar("ComboDamage", 7, ValueProp.Move),
    ];

    protected override bool ShouldGlowGoldInternal => Charge.IsCombo(this, 3);

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {
        var dmg = Charge.IsCombo(this, 3)
            ? DynamicVars["ComboDamage"].BaseValue
            : DynamicVars.Damage.BaseValue;
        var stored = DynamicVars.Damage.BaseValue;
        DynamicVars.Damage.BaseValue = dmg;
        try { await CommonActions.CardAttack(this, play).Execute(choiceContext); }
        finally { DynamicVars.Damage.BaseValue = stored; }
    }

    protected override void OnUpgrade()
    {
        DynamicVars.Damage.UpgradeValueBy(2m);
        DynamicVars["ComboDamage"].UpgradeValueBy(3m);
    }
}
