// Auto-generated by tools/generate_blake_kit.py — edit kit definition, then re-run.
using System.Linq;
using BaseLib.Utils;
using Blake.BlakeCode;
using Blake.BlakeCode.Powers;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;

namespace Blake.BlakeCode.Cards.Common;

public sealed class GuardUp() : BlakeCard(1, CardType.Skill, CardRarity.Common, TargetType.None)
{
    public override bool GainsBlock => true;
    protected override IEnumerable<DynamicVar> CanonicalVars =>
    [
        new BlockVar(6, ValueProp.Move),
        new BlockVar("HighBlock", 9, ValueProp.Move),
    ];

    protected override bool ShouldGlowGoldInternal => Charge.Get(Owner) > Charge.GetBase(Owner);

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {
        var above = Charge.Get(Owner) > Charge.GetBase(Owner);
        var amt = above ? DynamicVars["HighBlock"].BaseValue : DynamicVars.Block.BaseValue;
        var stored = DynamicVars.Block.BaseValue;
        DynamicVars.Block.BaseValue = amt;
        try { await CommonActions.CardBlock(this, play); }
        finally { DynamicVars.Block.BaseValue = stored; }
    }

    protected override void OnUpgrade()
    {
        DynamicVars.Block.UpgradeValueBy(2m);
        DynamicVars["HighBlock"].UpgradeValueBy(3m);
    }
}
