// Auto-generated by tools/generate_blake_kit.py — edit kit definition, then re-run.
using System.Linq;
using BaseLib.Utils;
using Blake.BlakeCode;
using Blake.BlakeCode.Powers;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;

namespace Blake.BlakeCode.Cards.Basic;

public sealed class Haymaker() : BlakeCard(1, CardType.Attack, CardRarity.Basic, TargetType.AnyEnemy)
{
    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new DynamicVar("Bonus", 6)];

    protected override IEnumerable<IHoverTip> ExtraHoverTips =>
    [
        BlakeTips.Unleash,
        BlakeTips.Charge,
    ];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {
        var bonus = IsUpgraded ? DynamicVars["Bonus"].IntValue : 0;
        var dmg = await Charge.Unleash(choiceContext, Owner, this, reset: true, flatBonus: bonus);
        if (play.Target is not null && dmg > 0)
        {
            await CreatureCmd.Damage(choiceContext, play.Target, dmg, ValueProp.Move, Owner.Creature, this);
        }
    }

    protected override void OnUpgrade()
    {
        // +flat on Unleash via IsUpgraded check
    }
}
