<Project Sdk="Microsoft.NET.Sdk" InitialTargets="CheckDependencyPaths">
    <Import Project=".\Sts2PathDiscovery.props"/>
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>TradingPost</RootNamespace>

        <AppOutputBase>$(MSBuildProjectDirectory)\</AppOutputBase>
        <PathMap>$(AppOutputBase)=.\</PathMap>
        <NoWarn>$(NoWarn);MSB3270</NoWarn>
    </PropertyGroup>

    <ItemGroup Condition="Exists('$(Sts2DataDir)')">
        <Reference Include="0Harmony">
            <HintPath>$(Sts2DataDir)/0Harmony.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="sts2">
            <HintPath>$(Sts2DataDir)/sts2.dll</HintPath>
            <Private>false</Private>
        </Reference>
        <Reference Include="GodotSharp">
            <HintPath>$(Sts2DataDir)/GodotSharp.dll</HintPath>
            <Private>false</Private>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Krafs.Publicizer" Version="2.3.0" PrivateAssets="All"/>
        <Publicize Include="sts2" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="TradingPost.json"/>
    </ItemGroup>

    <Target Name="CheckDependencyPaths">
        <Error
                Text=" Slay the Spire 2 data not found at path '$(Sts2DataDir)'"
                Condition="'$(Sts2DataDir)' == '' or !Exists('$(Sts2DataDir)')"/>
    </Target>

    <Target Name="CopyToModsFolderOnBuild" AfterTargets="PostBuildEvent">
        <Message Text="Copying .dll .pdb and .json to mods folder." Importance="high"/>
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/"/>
        <Copy SourceFiles="TradingPost.json" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/"/>
        <Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/"/>
        <Copy SourceFiles="assets\option_trade.png" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/" Condition="Exists('assets\option_trade.png')"/>
        <Copy SourceFiles="assets\menu_banner.png" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/" Condition="Exists('assets\menu_banner.png')"/>
        <Copy SourceFiles="assets\icon_gold.png" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/" Condition="Exists('assets\icon_gold.png')"/>
        <Copy SourceFiles="assets\icon_card.png" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/" Condition="Exists('assets\icon_card.png')"/>
        <Copy SourceFiles="assets\icon_trade.png" DestinationFolder="$(ModsPath)$(MSBuildProjectName)/" Condition="Exists('assets\icon_trade.png')"/>
    </Target>
</Project>
