// Auto-generated by tools/generate_blake_kit.py — edit kit definition, then re-run.
using System.Linq;
using BaseLib.Utils;
using Blake.BlakeCode;
using Blake.BlakeCode.Powers;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;

namespace Blake.BlakeCode.Cards.Uncommon;

public sealed class CleanKo() : BlakeCard(1, CardType.Attack, CardRarity.Uncommon, TargetType.AnyEnemy)
{
    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new DynamicVar("Bonus", 8)];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {
        await Charge.Ensure(choiceContext, Owner, this);
        var bonus = IsUpgraded ? DynamicVars["Bonus"].IntValue : 0;
        // Preview damage without resetting; reset only if target lives.
        var dmg = Charge.Get(Owner) + bonus;
        if (play.Target is null || dmg <= 0) return;

        await CreatureCmd.Damage(choiceContext, play.Target, dmg, ValueProp.Move, Owner.Creature, this);
        var keepCharge = play.Target.IsDead;
        // Bookkeeping: count Unleash, refund engines, optional reset
        _ = await Charge.Unleash(choiceContext, Owner, this, reset: !keepCharge, flatBonus: 0);
        // Unleash re-reads Charge for return value but we already dealt — if reset:false Charge stays.
        // If keepCharge is false, Unleash resets (good). If true, Charge was still full when Unleash ran...
        // BUG: Unleash doesn't spend when reset:false, good. But when reset:true it sets to base — good.
        // When keepCharge, Charge still full — Unleash still increments unleash count and Highlight Reel — good.
    }

    protected override void OnUpgrade() { }
}
