// Auto-generated by tools/generate_blake_kit.py — edit kit definition, then re-run.
using System.Linq;
using BaseLib.Utils;
using Blake.BlakeCode;
using Blake.BlakeCode.Powers;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;

namespace Blake.BlakeCode.Cards.Uncommon;

public sealed class Pressure() : BlakeCard(1, CardType.Attack, CardRarity.Uncommon, TargetType.AnyEnemy)
{
    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new DynamicVar("Bonus", 4)];

    protected override IEnumerable<IHoverTip> ExtraHoverTips =>
    [
        BlakeTips.Charge,
    ];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {
        await Charge.Ensure(choiceContext, Owner, this);
        var half = Charge.Get(Owner) / 2;
        if (IsUpgraded) half += DynamicVars["Bonus"].IntValue;
        if (play.Target is not null && half > 0)
            await CreatureCmd.Damage(choiceContext, play.Target, half, ValueProp.Move, Owner.Creature, this);
    }

    protected override void OnUpgrade() { }
}
