// Auto-generated by tools/generate_blake_kit.py — edit kit definition, then re-run.
using System.Linq;
using BaseLib.Utils;
using Blake.BlakeCode;
using Blake.BlakeCode.Powers;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;

namespace Blake.BlakeCode.Cards.Uncommon;

public sealed class Redline() : BlakeCard(1, CardType.Skill, CardRarity.Uncommon, TargetType.None)
{
    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new DynamicVar("Threshold", 20)];

    protected override IEnumerable<IHoverTip> ExtraHoverTips =>
    [
        BlakeTips.Rev,
        BlakeTips.Charge,
    ];

    protected override bool ShouldGlowGoldInternal =>
        Charge.Get(Owner) >= DynamicVars["Threshold"].IntValue;

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {
        await Charge.Rev(choiceContext, Owner, 1, this);
        if (Charge.Get(Owner) >= DynamicVars["Threshold"].IntValue)
            await Charge.Rev(choiceContext, Owner, 1, this);
    }

    protected override void OnUpgrade()
    {
        DynamicVars["Threshold"].UpgradeValueBy(-8m);
    }
}
