// Auto-generated by tools/generate_blake_kit.py — edit kit definition, then re-run.
using System.Linq;
using BaseLib.Utils;
using Blake.BlakeCode;
using Blake.BlakeCode.Powers;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;

namespace Blake.BlakeCode.Cards.Uncommon;

public sealed class Slipstream() : BlakeCard(1, CardType.Power, CardRarity.Uncommon, TargetType.None)
{
    protected override IEnumerable<DynamicVar> CanonicalVars =>
    [
        new DynamicVar("Threshold", 4),
    ];

    protected override IEnumerable<IHoverTip> ExtraHoverTips =>
    [
        BlakeTips.Rev,
        BlakeTips.Charge,
    ];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {
        if (Owner.Creature is null) return;
        await PowerCmd.Apply<SlipstreamPower>(
            choiceContext,
            Owner.Creature,
            DynamicVars["Threshold"].IntValue,
            Owner.Creature,
            this);
    }

    protected override void OnUpgrade()
    {
                DynamicVars["Threshold"].UpgradeValueBy(-1m);
    }
}
