// Auto-generated by tools/generate_blake_kit.py — edit kit definition, then re-run.
using System.Linq;
using BaseLib.Utils;
using Blake.BlakeCode;
using Blake.BlakeCode.Powers;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;

namespace Blake.BlakeCode.Cards.Rare;

public sealed class FalconPunch() : BlakeCard(3, CardType.Attack, CardRarity.Rare, TargetType.AnyEnemy)
{

    protected override IEnumerable<IHoverTip> ExtraHoverTips =>
    [
        BlakeTips.Unleash,
        BlakeTips.Charge,
        BlakeTips.FollowThrough,
    ];
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {
        var dmg = await Charge.Unleash(choiceContext, Owner, this, reset: true, multiplier: 2m);
        if (play.Target is null || dmg <= 0 || Owner.Creature is null) return;

        var results = await CreatureCmd.Damage(
            choiceContext, play.Target, dmg, ValueProp.Move, Owner.Creature, this);
        // Follow-Through: overkill hits another enemy
        var overkill = results.Sum(r => r.OverkillDamage);
        if (overkill > 0 && Owner.Creature.CombatState is not null)
        {
            var next = Owner.Creature.CombatState.HittableEnemies
                .FirstOrDefault(e => e != play.Target && e.IsAlive);
            if (next is not null)
                await CreatureCmd.Damage(choiceContext, next, overkill, ValueProp.Move, Owner.Creature, this);
        }
    }

    protected override void OnUpgrade()
    {
        EnergyCost.UpgradeBy(-1);
    }
}
