// Auto-generated by tools/generate_blake_kit.py — edit kit definition, then re-run.
using System.Linq;
using BaseLib.Utils;
using Blake.BlakeCode;
using Blake.BlakeCode.Powers;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;

namespace Blake.BlakeCode.Cards.Rare;

public sealed class MuscleMemory() : BlakeCard(1, CardType.Skill, CardRarity.Rare, TargetType.None)
{
    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {
        var times = 1 + Charge.UnleashCount(Owner);
        await Charge.Rev(choiceContext, Owner, times, this);
    }

    protected override void OnUpgrade()
    {
        EnergyCost.UpgradeBy(-1);
    }
}
