// Auto-generated by tools/generate_blake_kit.py — edit kit definition, then re-run.
using System.Linq;
using BaseLib.Utils;
using Blake.BlakeCode;
using Blake.BlakeCode.Powers;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;

namespace Blake.BlakeCode.Cards.Rare;

public sealed class PhotoFinish() : BlakeCard(1, CardType.Attack, CardRarity.Rare, TargetType.AnyEnemy)
{
    protected override IEnumerable<DynamicVar> CanonicalVars =>
    [
        new HealVar(8),
        new GoldVar(15),
    ];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {
        await Charge.Ensure(choiceContext, Owner, this);
        var dmg = Charge.Get(Owner);
        // Spend the punch (reset Charge)
        _ = await Charge.Unleash(choiceContext, Owner, this, reset: true);
        if (play.Target is not null && dmg > 0)
            await CreatureCmd.Damage(choiceContext, play.Target, dmg, ValueProp.Move, Owner.Creature, this);

        // Sweetspot: last enemy dead after this
        var combat = Owner.Creature?.CombatState;
        if (combat is not null && !combat.HittableEnemies.Any(e => e.IsAlive))
        {
            if (Owner.Creature is not null)
                await CreatureCmd.Heal(Owner.Creature, DynamicVars.Heal.IntValue);
            await PlayerCmd.GainGold(DynamicVars.Gold.IntValue, Owner);
        }
    }

    protected override void OnUpgrade()
    {
        DynamicVars.Heal.UpgradeValueBy(4m);
        DynamicVars.Gold.UpgradeValueBy(10m);
    }
}
