#!/usr/bin/env python3
"""Emit Whitney reward card C# + catalog from whitney_kit_def.json."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KIT = json.loads((ROOT / "tools" / "whitney_kit_def.json").read_text(encoding="utf-8"))
CODE = ROOT / "mods" / "whitney" / "WhitneyCode" / "Cards"
LOC = ROOT / "mods" / "whitney" / "Whitney" / "localization" / "eng" / "cards.json"
DOCS = ROOT / "docs" / "whitney-cards.json"
PORTRAITS = ROOT / "mods" / "whitney" / "Whitney" / "images" / "card_portraits"
PORTRAITS_BIG = PORTRAITS / "big"

HEADER = """// Auto-generated by tools/emit_whitney_cards.py
using BaseLib.Utils;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.HoverTips;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;
using Whitney.WhitneyCode.Powers;

namespace Whitney.WhitneyCode.Cards.{ns};

public sealed class {name}() : WhitneyCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{body}}}
"""


def loc_key(name: str) -> str:
    snake = []
    for i, ch in enumerate(name):
        if ch.isupper() and i:
            snake.append("_")
        snake.append(ch.upper())
    return "WHITNEY-" + "".join(snake)


def emit(c: dict) -> str:
    tmpl = c["tmpl"]
    name = c["name"]
    rarity = c["rarity"]
    ns = rarity
    cost = c["cost"]
    ctype = c["card_type"]
    target = c["target"]
    if target == "None":
        target = "Self"

    props = []
    vars_ = []
    tips = []
    play = []
    up = []
    ink_cost_prop = ""

    kws = list(c.get("keywords") or [])
    if "Exhaust" in kws:
        props.append("    public override IEnumerable<CardKeyword> CanonicalKeywords => [CardKeyword.Exhaust];")

    gains_block = False
    if ctype == "Skill" and ("block" in tmpl or tmpl.startswith("block") or "Block" in str(c.get("lines"))):
        gains_block = True

    if "ink" in tmpl or "Ink" in str(c.get("lines")):
        tips.append("HoverTipFactory.FromPower<InkPower>()")
    if "attune" in tmpl or "Attunement" in str(c.get("lines")):
        tips.append("HoverTipFactory.FromPower<AttunementPower>()")
    if "weak" in tmpl.lower() or "Weak" in str(c.get("lines")):
        tips.append("HoverTipFactory.FromPower<WeakPower>()")
    if "vuln" in tmpl or "Vulnerable" in str(c.get("lines")):
        tips.append("HoverTipFactory.FromPower<VulnerablePower>()")
    if "vigor" in tmpl or "Vigor" in str(c.get("lines")):
        tips.append("HoverTipFactory.FromPower<VigorPower>()")
    if "frail" in tmpl or "Frail" in str(c.get("lines")):
        tips.append("HoverTipFactory.FromPower<FrailPower>()")
    # de-dupe
    seen = []
    for t in tips:
        if t not in seen:
            seen.append(t)
    if seen:
        props.append(
            "    protected override IEnumerable<IHoverTip> ExtraHoverTips =>\n    [\n        "
            + ",\n        ".join(seen)
            + ",\n    ];"
        )

    ink_cost = c.get("ink_cost")
    if ink_cost:
        ink_cost_prop = f"    protected override int InkCost => {ink_cost};\n"

    def add_dmg():
        vars_.append(f"        new DamageVar({c['dmg']}, ValueProp.Move),")

    def add_block():
        vars_.append(f"        new BlockVar({c['block']}, ValueProp.Move),")

    def add_cards():
        vars_.append(f"        new CardsVar({c['cards']}),")

    def add_repeat():
        vars_.append(f"        new RepeatVar({c['hits']}),")

    def add_energy():
        vars_.append(f"        new EnergyVar({c['energy']}),")

    def add_dyn(key, val):
        vars_.append(f'        new DynamicVar("{key}", {val}),')

    def up_dmg():
        if c.get("up_dmg"):
            up.append(f"        DynamicVars.Damage.UpgradeValueBy({c['up_dmg']}m);")

    def up_block():
        if c.get("up_block"):
            up.append(f"        DynamicVars.Block.UpgradeValueBy({c['up_block']}m);")

    def up_cards():
        if c.get("up_cards"):
            up.append(f"        DynamicVars.Cards.UpgradeValueBy({c['up_cards']}m);")

    def up_hits():
        if c.get("up_hits"):
            up.append(f"        DynamicVars.Repeat.UpgradeValueBy({c['up_hits']}m);")

    def up_dyn(key, field="up_" + key.lower() if False else None):
        pass

    # Template implementations
    if tmpl == "attack_ink":
        add_dmg(); add_dyn("Ink", c["ink"])
        play.append("        await CommonActions.CardAttack(this, play).Execute(choiceContext);")
        play.append("        await Ink.Gain(choiceContext, Owner, DynamicVars[\"Ink\"].IntValue, this);")
        up_dmg()
        if c.get("up_ink"):
            up.append(f'        DynamicVars["Ink"].UpgradeValueBy({c["up_ink"]}m);')
    elif tmpl == "block_ink":
        gains_block = True
        add_block(); add_dyn("Ink", c["ink"])
        play.append("        await CommonActions.CardBlock(this, play);")
        play.append("        await Ink.Gain(choiceContext, Owner, DynamicVars[\"Ink\"].IntValue, this);")
        up_block()
        if c.get("up_ink"):
            up.append(f'        DynamicVars["Ink"].UpgradeValueBy({c["up_ink"]}m);')
    elif tmpl == "attack_attune":
        add_dmg(); add_dyn("Attune", c["attune"])
        play.append("        await CommonActions.CardAttack(this, play).Execute(choiceContext);")
        play.append("""        if (Owner.Creature is not null)
            await PowerCmd.Apply<AttunementPower>(choiceContext, Owner.Creature, DynamicVars["Attune"].IntValue, Owner.Creature, this);""")
        up_dmg()
        if c.get("up_attune"):
            up.append(f'        DynamicVars["Attune"].UpgradeValueBy({c["up_attune"]}m);')
    elif tmpl == "block_attune":
        gains_block = True
        add_block(); add_dyn("Attune", c["attune"])
        play.append("        await CommonActions.CardBlock(this, play);")
        play.append("""        if (Owner.Creature is not null)
            await PowerCmd.Apply<AttunementPower>(choiceContext, Owner.Creature, DynamicVars["Attune"].IntValue, Owner.Creature, this);""")
        up_block()
        if c.get("up_attune"):
            up.append(f'        DynamicVars["Attune"].UpgradeValueBy({c["up_attune"]}m);')
    elif tmpl == "attack_hits_ink":
        add_dmg(); add_repeat(); add_dyn("Ink", c["ink"])
        play.append("        await CommonActions.CardAttack(this, play).WithHitCount(DynamicVars.Repeat.IntValue).Execute(choiceContext);")
        play.append("        await Ink.Gain(choiceContext, Owner, DynamicVars[\"Ink\"].IntValue, this);")
        up_dmg(); up_hits()
    elif tmpl == "draw_ink":
        add_cards(); add_dyn("Ink", c["ink"])
        play.append("        await CardPileCmd.Draw(choiceContext, DynamicVars.Cards.BaseValue, Owner);")
        play.append("        await Ink.Gain(choiceContext, Owner, DynamicVars[\"Ink\"].IntValue, this);")
        up_cards()
        if c.get("up_ink"):
            up.append(f'        DynamicVars["Ink"].UpgradeValueBy({c["up_ink"]}m);')
    elif tmpl == "weak_ink":
        add_dyn("Weak", c["weak"]); add_dyn("Ink", c["ink"])
        play.append("""        if (play.Target is not null)
            await PowerCmd.Apply<WeakPower>(choiceContext, play.Target, DynamicVars["Weak"].IntValue, Owner.Creature, this);""")
        play.append("        await Ink.Gain(choiceContext, Owner, DynamicVars[\"Ink\"].IntValue, this);")
        if c.get("up_weak"):
            up.append(f'        DynamicVars["Weak"].UpgradeValueBy({c["up_weak"]}m);')
    elif tmpl == "attack_vuln_ink":
        add_dmg(); add_dyn("Vulnerable", c["vuln"]); add_dyn("Ink", c["ink"])
        play.append("        await CommonActions.CardAttack(this, play).Execute(choiceContext);")
        play.append("""        if (play.Target is not null)
            await PowerCmd.Apply<VulnerablePower>(choiceContext, play.Target, DynamicVars["Vulnerable"].IntValue, Owner.Creature, this);""")
        play.append("        await Ink.Gain(choiceContext, Owner, DynamicVars[\"Ink\"].IntValue, this);")
        up_dmg()
    elif tmpl == "block_draw":
        gains_block = True
        add_block(); add_cards()
        play.append("        await CommonActions.CardBlock(this, play);")
        play.append("        await CardPileCmd.Draw(choiceContext, DynamicVars.Cards.BaseValue, Owner);")
        up_block(); up_cards()
    elif tmpl == "ink_only":
        add_dyn("Ink", c["ink"])
        play.append("        await Ink.Gain(choiceContext, Owner, DynamicVars[\"Ink\"].IntValue, this);")
        if c.get("up_ink"):
            up.append(f'        DynamicVars["Ink"].UpgradeValueBy({c["up_ink"]}m);')
    elif tmpl == "attack_block":
        gains_block = True
        add_dmg(); add_block()
        play.append("        await CommonActions.CardAttack(this, play).Execute(choiceContext);")
        play.append("        await CommonActions.CardBlock(this, play);")
        up_dmg(); up_block()
    elif tmpl == "weak_block":
        gains_block = True
        add_block(); add_dyn("Weak", c["weak"])
        play.append("        await CommonActions.CardBlock(this, play);")
        play.append("""        if (play.Target is not null)
            await PowerCmd.Apply<WeakPower>(choiceContext, play.Target, DynamicVars["Weak"].IntValue, Owner.Creature, this);""")
        up_block()
    elif tmpl == "vigor_ink":
        add_dyn("Vigor", c["vigor"]); add_dyn("Ink", c["ink"])
        play.append("""        if (Owner.Creature is not null)
            await PowerCmd.Apply<VigorPower>(choiceContext, Owner.Creature, DynamicVars["Vigor"].IntValue, Owner.Creature, this);""")
        play.append("        await Ink.Gain(choiceContext, Owner, DynamicVars[\"Ink\"].IntValue, this);")
        if c.get("up_vigor"):
            up.append(f'        DynamicVars["Vigor"].UpgradeValueBy({c["up_vigor"]}m);')
    elif tmpl == "attack_block_ink":
        gains_block = True
        add_dmg(); add_block(); add_dyn("Ink", c["ink"])
        play.append("        await CommonActions.CardAttack(this, play).Execute(choiceContext);")
        play.append("        await CommonActions.CardBlock(this, play);")
        play.append("        await Ink.Gain(choiceContext, Owner, DynamicVars[\"Ink\"].IntValue, this);")
        up_dmg(); up_block()
    elif tmpl == "attack_weak_all_ink":
        add_dmg(); add_dyn("Weak", c["weak"]); add_dyn("Ink", c["ink"])
        play.append("        await CommonActions.CardAttack(this, play).Execute(choiceContext);")
        play.append("""        var combat = Owner.Creature?.CombatState;
        if (combat is not null)
        {
            foreach (var enemy in combat.HittableEnemies)
                await PowerCmd.Apply<WeakPower>(choiceContext, enemy, DynamicVars["Weak"].IntValue, Owner.Creature, this);
        }""")
        play.append("        await Ink.Gain(choiceContext, Owner, DynamicVars[\"Ink\"].IntValue, this);")
        up_dmg()
    elif tmpl == "ink_spend_attack":
        add_dmg()
        play.append(f"        if (!await Ink.TrySpend(choiceContext, Owner, {c['ink_cost']}, this)) return;")
        play.append("        await CommonActions.CardAttack(this, play).Execute(choiceContext);")
        up_dmg()
    elif tmpl == "ink_spend_attune_attack":
        add_dmg()
        play.append(f"        if (!await Ink.TrySpend(choiceContext, Owner, {c['ink_cost']}, this)) return;")
        play.append("""        var bonus = Owner.Creature?.GetPower<AttunementPower>()?.Amount ?? 0;
        var stored = DynamicVars.Damage.BaseValue;
        DynamicVars.Damage.BaseValue = stored + bonus;
        try { await CommonActions.CardAttack(this, play).Execute(choiceContext); }
        finally { DynamicVars.Damage.BaseValue = stored; }""")
        up_dmg()
    elif tmpl == "weak_all_draw":
        add_dyn("Weak", c["weak"]); add_cards()
        play.append("""        var combat = Owner.Creature?.CombatState;
        if (combat is not null)
        {
            foreach (var enemy in combat.HittableEnemies)
                await PowerCmd.Apply<WeakPower>(choiceContext, enemy, DynamicVars["Weak"].IntValue, Owner.Creature, this);
        }
        await CardPileCmd.Draw(choiceContext, DynamicVars.Cards.BaseValue, Owner);""")
        up_cards()
        if c.get("up_weak"):
            up.append(f'        DynamicVars["Weak"].UpgradeValueBy({c["up_weak"]}m);')
    elif tmpl == "block_draw_ink":
        gains_block = True
        add_block(); add_cards(); add_dyn("Ink", c["ink"])
        play.append("        await CommonActions.CardBlock(this, play);")
        play.append("        await CardPileCmd.Draw(choiceContext, DynamicVars.Cards.BaseValue, Owner);")
        play.append("        await Ink.Gain(choiceContext, Owner, DynamicVars[\"Ink\"].IntValue, this);")
        up_block(); up_cards()
    elif tmpl == "draw_energy_ink":
        add_cards(); add_energy(); add_dyn("Ink", c["ink"])
        play.append("        await CardPileCmd.Draw(choiceContext, DynamicVars.Cards.BaseValue, Owner);")
        play.append("        await PlayerCmd.GainEnergy(DynamicVars.Energy.IntValue, Owner);")
        play.append("        await Ink.Gain(choiceContext, Owner, DynamicVars[\"Ink\"].IntValue, this);")
        up_cards()
    elif tmpl == "weak_vuln":
        add_dyn("Weak", c["weak"]); add_dyn("Vulnerable", c["vuln"])
        play.append("""        if (play.Target is not null)
        {
            await PowerCmd.Apply<WeakPower>(choiceContext, play.Target, DynamicVars["Weak"].IntValue, Owner.Creature, this);
            await PowerCmd.Apply<VulnerablePower>(choiceContext, play.Target, DynamicVars["Vulnerable"].IntValue, Owner.Creature, this);
        }""")
        if c.get("up_weak"):
            up.append(f'        DynamicVars["Weak"].UpgradeValueBy({c["up_weak"]}m);')
            up.append(f'        DynamicVars["Vulnerable"].UpgradeValueBy({c["up_weak"]}m);')
    elif tmpl == "frail_block":
        gains_block = True
        add_block(); add_dyn("Frail", c["frail"])
        play.append("        await CommonActions.CardBlock(this, play);")
        play.append("""        if (play.Target is not null)
            await PowerCmd.Apply<FrailPower>(choiceContext, play.Target, DynamicVars["Frail"].IntValue, Owner.Creature, this);""")
        up_block()
    elif tmpl == "attune_only":
        add_dyn("Attune", c["attune"])
        play.append("""        if (Owner.Creature is not null)
            await PowerCmd.Apply<AttunementPower>(choiceContext, Owner.Creature, DynamicVars["Attune"].IntValue, Owner.Creature, this);""")
        if c.get("up_attune"):
            up.append(f'        DynamicVars["Attune"].UpgradeValueBy({c["up_attune"]}m);')
    elif tmpl == "ink_spend_block":
        gains_block = True
        add_block()
        play.append(f"        if (!await Ink.TrySpend(choiceContext, Owner, {c['ink_cost']}, this)) return;")
        play.append("        await CommonActions.CardBlock(this, play);")
        up_block()
    elif tmpl == "attack_attune_ink":
        add_dmg(); add_dyn("Attune", c["attune"]); add_dyn("Ink", c["ink"])
        play.append("        await CommonActions.CardAttack(this, play).Execute(choiceContext);")
        play.append("""        if (Owner.Creature is not null)
            await PowerCmd.Apply<AttunementPower>(choiceContext, Owner.Creature, DynamicVars["Attune"].IntValue, Owner.Creature, this);""")
        play.append("        await Ink.Gain(choiceContext, Owner, DynamicVars[\"Ink\"].IntValue, this);")
        up_dmg()
    elif tmpl == "block_vigor":
        gains_block = True
        add_block(); add_dyn("Vigor", c["vigor"])
        play.append("        await CommonActions.CardBlock(this, play);")
        play.append("""        if (Owner.Creature is not null)
            await PowerCmd.Apply<VigorPower>(choiceContext, Owner.Creature, DynamicVars["Vigor"].IntValue, Owner.Creature, this);""")
        up_block()
        if c.get("up_vigor"):
            up.append(f'        DynamicVars["Vigor"].UpgradeValueBy({c["up_vigor"]}m);')
    elif tmpl == "ink_energy":
        add_dyn("Ink", c["ink"]); add_energy()
        play.append("        await Ink.Gain(choiceContext, Owner, DynamicVars[\"Ink\"].IntValue, this);")
        play.append("        await PlayerCmd.GainEnergy(DynamicVars.Energy.IntValue, Owner);")
        if c.get("up_ink"):
            up.append(f'        DynamicVars["Ink"].UpgradeValueBy({c["up_ink"]}m);')
    elif tmpl == "brennen_power_ink_form":
        # applies ElementalFormPower
        add_dyn("Ink", c["ink"])
        play.append("""        if (Owner.Creature is not null)
            await PowerCmd.Apply<ElementalFormPower>(choiceContext, Owner.Creature, DynamicVars["Ink"].IntValue, Owner.Creature, this);""")
        if c.get("up_ink"):
            up.append(f'        DynamicVars["Ink"].UpgradeValueBy({c["up_ink"]}m);')
    elif tmpl == "ink_spend_aoe_debuff":
        add_dmg(); add_dyn("Weak", c["weak"]); add_dyn("Vulnerable", c["vuln"])
        play.append(f"        if (!await Ink.TrySpend(choiceContext, Owner, {c['ink_cost']}, this)) return;")
        play.append("        await CommonActions.CardAttack(this, play).Execute(choiceContext);")
        play.append("""        var combat = Owner.Creature?.CombatState;
        if (combat is not null)
        {
            foreach (var enemy in combat.HittableEnemies)
            {
                await PowerCmd.Apply<WeakPower>(choiceContext, enemy, DynamicVars["Weak"].IntValue, Owner.Creature, this);
                await PowerCmd.Apply<VulnerablePower>(choiceContext, enemy, DynamicVars["Vulnerable"].IntValue, Owner.Creature, this);
            }
        }""")
        up_dmg()
    elif tmpl == "ink_spend_aoe_debuff_single":
        add_dmg(); add_dyn("Weak", c["weak"]); add_dyn("Vulnerable", c["vuln"])
        play.append(f"        if (!await Ink.TrySpend(choiceContext, Owner, {c['ink_cost']}, this)) return;")
        play.append("        await CommonActions.CardAttack(this, play).Execute(choiceContext);")
        play.append("""        if (play.Target is not null)
        {
            await PowerCmd.Apply<WeakPower>(choiceContext, play.Target, DynamicVars["Weak"].IntValue, Owner.Creature, this);
            await PowerCmd.Apply<VulnerablePower>(choiceContext, play.Target, DynamicVars["Vulnerable"].IntValue, Owner.Creature, this);
        }""")
        up_dmg()
    elif tmpl == "weak_vuln_all":
        add_dyn("Weak", c["weak"]); add_dyn("Vulnerable", c["vuln"])
        play.append("""        var combat = Owner.Creature?.CombatState;
        if (combat is not null)
        {
            foreach (var enemy in combat.HittableEnemies)
            {
                await PowerCmd.Apply<WeakPower>(choiceContext, enemy, DynamicVars["Weak"].IntValue, Owner.Creature, this);
                await PowerCmd.Apply<VulnerablePower>(choiceContext, enemy, DynamicVars["Vulnerable"].IntValue, Owner.Creature, this);
            }
        }""")
        if c.get("up_weak"):
            up.append(f'        DynamicVars["Weak"].UpgradeValueBy({c["up_weak"]}m);')
            up.append(f'        DynamicVars["Vulnerable"].UpgradeValueBy({c["up_weak"]}m);')
    elif tmpl == "ink_spend_draw_energy":
        add_cards(); add_energy()
        play.append(f"        if (!await Ink.TrySpend(choiceContext, Owner, {c['ink_cost']}, this)) return;")
        play.append("        await CardPileCmd.Draw(choiceContext, DynamicVars.Cards.BaseValue, Owner);")
        play.append("        await PlayerCmd.GainEnergy(DynamicVars.Energy.IntValue, Owner);")
        up_cards()
    elif tmpl in ("power_attune_tick", "power_draw_tick", "power_block_tick", "power_vigor_tick",
                  "power_ink_on_attack", "power_ink_on_block", "power_ink_on_skill"):
        # Simplified: apply strength of passive via existing ElementalFormPower pattern for ink tick;
        # for other powers emit stub that applies a matching simple power or just ink form.
        # Use ElementalFormPower for ink ticks; Attunement for attune; skip complex for now by using ElementalFormPower/Ink gain on play only as fallback
        if tmpl == "power_attune_tick":
            add_dyn("Attune", c.get("attune", 1))
            play.append("""        if (Owner.Creature is not null)
            await PowerCmd.Apply<AttunementPower>(choiceContext, Owner.Creature, DynamicVars["Attune"].IntValue, Owner.Creature, this);""")
            # Note: true tick powers need custom power classes; apply stack now as slice
        elif tmpl == "power_draw_tick":
            add_cards()
            play.append("        await CardPileCmd.Draw(choiceContext, DynamicVars.Cards.BaseValue, Owner);")
        elif tmpl == "power_block_tick":
            gains_block = True
            add_block()
            play.append("        await CommonActions.CardBlock(this, play);")
        elif tmpl == "power_vigor_tick":
            add_dyn("Vigor", c.get("vigor", 2))
            play.append("""        if (Owner.Creature is not null)
            await PowerCmd.Apply<VigorPower>(choiceContext, Owner.Creature, DynamicVars["Vigor"].IntValue, Owner.Creature, this);""")
        elif tmpl == "power_ink_on_attack":
            add_dyn("Ink", c["ink"])
            play.append("""        if (Owner.Creature is not null)
            await PowerCmd.Apply<ElementalFormPower>(choiceContext, Owner.Creature, DynamicVars["Ink"].IntValue, Owner.Creature, this);""")
        elif tmpl == "power_ink_on_block":
            add_dyn("Ink", c["ink"])
            play.append("""        if (Owner.Creature is not null)
            await PowerCmd.Apply<ElementalFormPower>(choiceContext, Owner.Creature, DynamicVars["Ink"].IntValue, Owner.Creature, this);""")
        elif tmpl == "power_ink_on_skill":
            add_dyn("Ink", c["ink"])
            play.append("""        if (Owner.Creature is not null)
            await PowerCmd.Apply<ElementalFormPower>(choiceContext, Owner.Creature, DynamicVars["Ink"].IntValue, Owner.Creature, this);""")
        for k in ("up_attune", "up_block", "up_vigor", "up_ink", "up_cards"):
            if c.get(k):
                key = k.replace("up_", "").title().replace("Attune", "Attune")
                if k == "up_attune":
                    up.append(f'        DynamicVars["Attune"].UpgradeValueBy({c[k]}m);')
                elif k == "up_block":
                    up.append(f"        DynamicVars.Block.UpgradeValueBy({c[k]}m);")
                elif k == "up_vigor":
                    up.append(f'        DynamicVars["Vigor"].UpgradeValueBy({c[k]}m);')
                elif k == "up_ink":
                    up.append(f'        DynamicVars["Ink"].UpgradeValueBy({c[k]}m);')
                elif k == "up_cards":
                    up.append(f"        DynamicVars.Cards.UpgradeValueBy({c[k]}m);")
    else:
        raise ValueError(f"Unknown tmpl {tmpl} for {name}")

    body_parts = []
    if ink_cost_prop:
        body_parts.append(ink_cost_prop.rstrip("\n"))
    if gains_block:
        body_parts.append("    public override bool GainsBlock => true;")
    body_parts.extend(props)
    if vars_:
        body_parts.append(
            "    protected override IEnumerable<DynamicVar> CanonicalVars =>\n    [\n"
            + "\n".join(vars_)
            + "\n    ];"
        )
    body_parts.append(
        "    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)\n    {\n"
        + "\n".join(play)
        + "\n    }"
    )
    if up:
        body_parts.append(
            "    protected override void OnUpgrade()\n    {\n"
            + "\n".join(up)
            + "\n    }"
        )

    body = "\n\n".join(body_parts) + "\n"
    return HEADER.format(
        ns=ns, name=name, cost=cost, ctype=ctype, rarity=rarity, target=target, body=body
    )


def main():
    loc = {}
    if LOC.exists():
        loc = json.loads(LOC.read_text(encoding="utf-8"))

    # keep basic hand loc
    catalog = [
        dict(id="travelersinkpot", name="Traveler's Inkpot", rarity="relic", type="Relic", cost=None,
             art="assets/whitney/travelersinkpot.png", lines=["At the start of each combat,", "gain 3 Ink."],
             keywords=["Ink"], stats="Starter", flavor="Never travel without a full pot."),
        dict(id="spark", name="Spark", rarity="basic", type="Attack", cost=1,
             art="assets/whitney/spark.jpg", lines=["Deal 6 damage."], keywords=[]),
        dict(id="ripple", name="Ripple", rarity="basic", type="Skill", cost=1,
             art="assets/whitney/ripple.jpg", lines=["Gain 5 Block."], keywords=["Block"]),
        dict(id="channelink", name="Channel Ink", rarity="basic", type="Skill", cost=1,
             art="assets/whitney/channelink.jpg", lines=["Gain 2 Ink."], keywords=["Ink"]),
        dict(id="noviceseal", name="Novice Seal", rarity="basic", type="Attack", cost=0,
             art="assets/whitney/noviceseal.jpg", lines=["Deal 5 damage.", "Apply 1 Weak.", "Gain 1 Ink."],
             keywords=["Weak", "Ink"]),
    ]

    ph = PORTRAITS / "card.png"
    big_ph = PORTRAITS_BIG / "card.png"

    for c in KIT:
        path = CODE / c["rarity"] / f"{c['name']}.cs"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(emit(c), encoding="utf-8")
        key = loc_key(c["name"])
        loc[f"{key}.title"] = c["title"]
        loc[f"{key}.description"] = "\n".join(c["lines"])
        stem = c["name"].lower()
        catalog.append({
            "id": stem,
            "name": c["title"],
            "rarity": c["rarity"].lower(),
            "type": c["card_type"],
            "cost": c["cost"],
            "art": f"assets/whitney/{stem}.jpg",
            "lines": [ln.replace("{Damage:diff()}", "N").replace("{Block:diff()}", "N")
                      .replace("{Ink:diff()}", "N").replace("{Attune:diff()}", "N")
                      .replace("{Weak:diff()}", "N").replace("{Vulnerable:diff()}", "N")
                      .replace("{Cards:diff()}", "N").replace("{Repeat:diff()}", "N")
                      .replace("{Vigor:diff()}", "N").replace("{Frail:diff()}", "N")
                      .replace("{Energy:energyIcons()}", "Energy")
                      for ln in c["lines"]],
            "keywords": c.get("keywords") or [],
            **({"element": c["element"]} if c.get("element") else {}),
        })
        # placeholder portraits if missing
        if ph.exists() and not (PORTRAITS / f"{stem}.png").exists():
            shutil = __import__("shutil")
            shutil.copy2(ph, PORTRAITS / f"{stem}.png")
            if big_ph.exists():
                shutil.copy2(big_ph, PORTRAITS_BIG / f"{stem}.png")

    LOC.write_text(json.dumps(loc, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    DOCS.write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    # also sync to kitpass docs if present
    kitpass = Path(r"C:\Users\4step\projects\sentou-koubou-brennen-kitpass\docs\whitney-cards.json")
    if kitpass.parent.exists():
        kitpass.write_text(json.dumps(catalog, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Emitted {len(KIT)} cards, catalog {len(catalog)}")


if __name__ == "__main__":
    import shutil  # noqa: F401 — used in main
    main()
