#!/usr/bin/env python3
"""Generate Blake's full card kit (Charge / Rev / Unleash / Sweetspot / Combo).

Basics (starter): Jab, Guard, RevUp, Haymaker
Rewards: 10 Common / 14 Uncommon / 10 Rare
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MOD = ROOT / "mods" / "blake"
CODE = MOD / "BlakeCode" / "Cards"
LOC = MOD / "Blake" / "localization" / "eng" / "cards.json"
DOCS = ROOT / "docs" / "blake-cards.json"
PORTRAITS = MOD / "Blake" / "images" / "card_portraits"
PORTRAITS_BIG = PORTRAITS / "big"

HEADER = """// Auto-generated by tools/generate_blake_kit.py — edit kit definition, then re-run.
using System.Linq;
using BaseLib.Utils;
using Blake.BlakeCode;
using Blake.BlakeCode.Powers;
using MegaCrit.Sts2.Core.Commands;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.GameActions.Multiplayer;
using MegaCrit.Sts2.Core.Localization.DynamicVars;
using MegaCrit.Sts2.Core.Models.Powers;
using MegaCrit.Sts2.Core.ValueProps;

namespace Blake.BlakeCode.Cards.{ns};
"""

# ---------------------------------------------------------------------------
# Kit definition
# ---------------------------------------------------------------------------
# class names must match PascalCase filenames

KIT: list[dict] = [
    # ===== BASIC =====
    dict(name="Jab", rarity="Basic", cost=1, card_type="Attack", target="AnyEnemy",
         tmpl="attack", dmg=6, up_dmg=3,
         title="Jab", lines=["Deal {Damage:diff()} damage."]),
    dict(name="Guard", rarity="Basic", cost=1, card_type="Skill", target="None",
         tmpl="block", block=5, up_block=3,
         title="Guard", lines=["Gain {Block:diff()} [gold]Block[/gold]."]),
    dict(name="RevUp", rarity="Basic", cost=1, card_type="Skill", target="None",
         tmpl="rev", up_draw=1,
         title="Rev Up", lines=["[gold]Rev[/gold]."], up_lines=["[gold]Rev[/gold].", "Draw {Cards:diff()} card."]),
    dict(name="Haymaker", rarity="Basic", cost=1, card_type="Attack", target="AnyEnemy",
         tmpl="unleash", up_flat=6,
         title="Haymaker",
         lines=["[gold]Unleash[/gold] — deal damage equal to your [gold]Charge[/gold]."],
         up_lines=["[gold]Unleash[/gold] — deal damage equal to your [gold]Charge[/gold] + {Bonus:diff()}."]),

    # ===== COMMON =====
    dict(name="WarmEngine", rarity="Common", cost=1, card_type="Skill", target="None",
         tmpl="rev_block", block=3, up_block=3,
         title="Warm Engine", lines=["[gold]Rev[/gold].", "Gain {Block:diff()} [gold]Block[/gold]."]),
    dict(name="WindUp", rarity="Common", cost=0, card_type="Skill", target="None",
         tmpl="rev", exhaust=True, up_draw=1,
         title="Wind-Up", lines=["[gold]Rev[/gold]."], up_lines=["[gold]Rev[/gold].", "Draw {Cards:diff()} card."]),
    dict(name="RaptorBoost", rarity="Common", cost=2, card_type="Attack", target="AnyEnemy",
         tmpl="attack_rev", dmg=6, up_dmg=3,
         title="Raptor Boost", lines=["Deal {Damage:diff()} damage.", "[gold]Rev[/gold]."]),
    dict(name="GuardUp", rarity="Common", cost=1, card_type="Skill", target="None",
         tmpl="guard_up", block=6, high_block=9, up_block=2, up_high=3,
         title="Guard Up",
         lines=["Gain {Block:diff()} [gold]Block[/gold].", "If your [gold]Charge[/gold] is above base, gain {HighBlock:diff()} instead."]),
    dict(name="OneTwo", rarity="Common", cost=1, card_type="Attack", target="AnyEnemy",
         tmpl="attack_hits_combo", dmg=4, hits=2, combo=3, up_dmg=2,
         title="One-Two",
         lines=["Deal {Damage:diff()} damage twice.", "[gold]Combo 3[/gold]: draw 1."]),
    dict(name="DashAttack", rarity="Common", cost=0, card_type="Attack", target="AnyEnemy",
         tmpl="dash", dmg=3, combo_dmg=7, combo=3, up_dmg=2, up_combo=3,
         title="Dash Attack",
         lines=["Deal {Damage:diff()} damage.", "[gold]Combo 3[/gold]: deal {ComboDamage:diff()} instead."]),
    dict(name="ShoulderCheck", rarity="Common", cost=1, card_type="Attack", target="AnyEnemy",
         tmpl="attack_sweetspot_weak", dmg=8, weak=2, up_dmg=3,
         title="Shoulder Check",
         lines=["Deal {Damage:diff()} damage.", "[gold]Sweetspot[/gold] — enemy intends to Attack: apply {Weak:diff()} [gold]Weak[/gold]."]),
    dict(name="FalconDive", rarity="Common", cost=1, card_type="Attack", target="AnyEnemy",
         tmpl="attack_fatal_rev", dmg=7, energy=1, up_dmg=3,
         title="Falcon Dive",
         lines=["Deal {Damage:diff()} damage.", "If Fatal, gain {Energy:energyIcons()} and [gold]Rev[/gold]."]),
    dict(name="Sidestep", rarity="Common", cost=0, card_type="Skill", target="None",
         tmpl="block", block=3, up_block=2, retain=True,
         title="Sidestep", lines=["Gain {Block:diff()} [gold]Block[/gold]."]),
    dict(name="ShowMeYourMoves", rarity="Common", cost=0, card_type="Skill", target="AnyEnemy",
         tmpl="weak_draw", weak=1, cards=1, up_weak=1,
         title="Show Me Your Moves",
         lines=["Apply {Weak:diff()} [gold]Weak[/gold].", "Draw {Cards:diff()} card."]),

    # ===== UNCOMMON =====
    dict(name="FullThrottle", rarity="Uncommon", cost=2, card_type="Skill", target="None",
         tmpl="rev_twice", up_cost=1,
         title="Full Throttle", lines=["[gold]Rev[/gold] twice."]),
    dict(name="Ignition", rarity="Uncommon", cost=0, card_type="Skill", target="None",
         tmpl="rev", exhaust=True, up_draw=1,
         title="Ignition", lines=["[gold]Rev[/gold]."], up_lines=["[gold]Rev[/gold].", "Draw {Cards:diff()} card."]),
    dict(name="Redline", rarity="Uncommon", cost=1, card_type="Skill", target="None",
         tmpl="redline", threshold=20, up_threshold=-8,
         title="Redline",
         lines=["[gold]Rev[/gold].", "If your [gold]Charge[/gold] is {Threshold:diff()} or more, [gold]Rev[/gold] again."]),
    dict(name="Slipstream", rarity="Uncommon", cost=1, card_type="Power", target="None",
         tmpl="power", power="SlipstreamPower", amount=4, up_amount=-1, amount_key="Threshold",
         title="Slipstream",
         lines=["Whenever you play your {Threshold:diff()}th card in a turn, [gold]Rev[/gold]."]),
    dict(name="PerfectShield", rarity="Uncommon", cost=1, card_type="Skill", target="None",
         tmpl="perfect_shield", block=8, up_block=3,
         title="Perfect Shield",
         lines=["Gain {Block:diff()} [gold]Block[/gold].", "If you block ALL attack damage this turn, [gold]Rev[/gold] at end of turn."]),
    dict(name="Pressure", rarity="Uncommon", cost=1, card_type="Attack", target="AnyEnemy",
         tmpl="pressure", up_flat=4,
         title="Pressure",
         lines=["Deal damage equal to half your [gold]Charge[/gold].", "Doesn't reset."],
         up_lines=["Deal damage equal to half your [gold]Charge[/gold] + {Bonus:diff()}.", "Doesn't reset."]),
    dict(name="StoredPower", rarity="Uncommon", cost=1, card_type="Skill", target="None",
         tmpl="stored_power", fraction="half", up_fraction="two_thirds",
         title="Stored Power",
         lines=["Gain [gold]Block[/gold] equal to half your [gold]Charge[/gold]."],
         up_lines=["Gain [gold]Block[/gold] equal to two-thirds of your [gold]Charge[/gold]."]),
    dict(name="FalconKick", rarity="Uncommon", cost=2, card_type="Attack", target="AllEnemies",
         tmpl="unleash_aoe", up_flat=8,
         title="Falcon Kick",
         lines=["[gold]Unleash[/gold] — deal damage equal to your [gold]Charge[/gold] to ALL enemies."],
         up_lines=["[gold]Unleash[/gold] — deal [gold]Charge[/gold] + {Bonus:diff()} damage to ALL enemies."]),
    dict(name="CleanKo", rarity="Uncommon", cost=1, card_type="Attack", target="AnyEnemy",
         tmpl="clean_ko", up_flat=8,
         title="Clean KO",
         lines=["Deal damage equal to your [gold]Charge[/gold].", "If this kills the enemy, don't reset."],
         up_lines=["Deal damage equal to your [gold]Charge[/gold] + {Bonus:diff()}.", "If this kills the enemy, don't reset."]),
    dict(name="KneeOfJustice", rarity="Uncommon", cost=1, card_type="Attack", target="AnyEnemy",
         tmpl="knee", dmg=8, sweet=22, up_dmg=2, up_sweet=6,
         title="Knee of Justice",
         lines=["Deal {Damage:diff()} damage.", "[gold]Sweetspot[/gold] — enemy intends to Attack: deal {SweetDamage:diff()} instead."]),
    dict(name="Grab", rarity="Uncommon", cost=1, card_type="Attack", target="AnyEnemy",
         tmpl="grab", dmg=6, up_dmg=3,
         title="Grab",
         lines=["The target loses ALL [gold]Block[/gold], then deal {Damage:diff()} damage."]),
    dict(name="SpotDodge", rarity="Uncommon", cost=1, card_type="Skill", target="None",
         tmpl="spot_dodge", exhaust=True, up_cost=0,
         title="Spot Dodge",
         lines=["The next time an enemy attacks you this turn, it misses entirely."]),
    dict(name="Yes", rarity="Uncommon", cost=0, card_type="Skill", target="None",
         tmpl="yes", energy=2, cards=2, exhaust=True, up_energy=1,
         title="YES!",
         lines=["If you [gold]Unleashed[/gold] this turn: gain {Energy:energyIcons()} and draw {Cards:diff()} cards."]),
    dict(name="WarmUpLap", rarity="Uncommon", cost=1, card_type="Skill", target="None",
         tmpl="warmup", cards=2, combo=4, energy=1, up_cards=1,
         title="Warm-Up Lap",
         lines=["Draw {Cards:diff()} cards.", "[gold]Combo 4[/gold]: gain {Energy:energyIcons()}."]),

    # ===== RARE =====
    dict(name="FalconPunch", rarity="Rare", cost=3, card_type="Attack", target="AnyEnemy",
         tmpl="falcon_punch", up_cost=2,
         title="FALCON PUNCH",
         lines=["[gold]Unleash[/gold] — deal damage equal to DOUBLE your [gold]Charge[/gold].", "[gold]Follow-Through[/gold] (excess damage hits another enemy)."]),
    dict(name="BlueFalcon", rarity="Rare", cost=3, card_type="Attack", target="AllEnemies",
         tmpl="blue_falcon", exhaust=True, up_cost=2,
         title="Blue Falcon",
         lines=["Deal damage equal to your [gold]Charge[/gold] to ALL enemies.", "This doesn't reset your [gold]Charge[/gold]."]),
    dict(name="GDiffuser", rarity="Rare", cost=2, card_type="Power", target="None",
         tmpl="power", power="GDiffuserPower", amount=1, up_cost=1,
         title="G-Diffuser",
         lines=["At the start of your turn, [gold]Rev[/gold]."]),
    dict(name="SuperArmor", rarity="Rare", cost=2, card_type="Power", target="None",
         tmpl="power", power="SuperArmorPower", amount=1, up_cost=1,
         title="Super Armor",
         lines=["Your [gold]Charge[/gold] can no longer be halved."]),
    dict(name="ChampionsFist", rarity="Rare", cost=1, card_type="Power", target="None",
         tmpl="power", power="ChampionFistPower", amount=3, up_amount=2, amount_key="Base",
         title="Champion's Fist",
         lines=["Increase your base [gold]Charge[/gold] by {Base:diff()}."]),
    dict(name="MuscleMemory", rarity="Rare", cost=1, card_type="Skill", target="None",
         tmpl="muscle_memory", up_cost=0,
         title="Muscle Memory",
         lines=["[gold]Rev[/gold] once, plus once more for each time you've [gold]Unleashed[/gold] this combat."]),
    dict(name="HighlightReel", rarity="Rare", cost=1, card_type="Power", target="None",
         tmpl="power", power="HighlightReelPower", amount=2, up_cost=0,
         title="Highlight Reel",
         lines=["Whenever you [gold]Unleash[/gold], gain {Energy:energyIcons()} and draw {Cards:diff()} cards."]),
    dict(name="HeatHaze", rarity="Rare", cost=2, card_type="Power", target="None",
         tmpl="power", power="HeatHazePower", amount=4, up_amount=2, amount_key="Haze",
         title="Heat Haze",
         lines=["Whenever you [gold]Rev[/gold], deal {Haze:diff()} damage to ALL enemies."]),
    dict(name="HardRead", rarity="Rare", cost=1, card_type="Skill", target="AnyEnemy",
         tmpl="hard_read", exhaust=True, up_energy=1,
         title="Hard Read",
         lines=["[gold]Sweetspot[/gold] — if the enemy intends to Attack: it is [gold]Stunned[/gold].", "Otherwise, draw 1 card."],
         up_lines=["[gold]Sweetspot[/gold] — if the enemy intends to Attack: it is [gold]Stunned[/gold] and gain {Energy:energyIcons()}.", "Otherwise, draw 1 card."]),
    dict(name="PhotoFinish", rarity="Rare", cost=1, card_type="Attack", target="AnyEnemy",
         tmpl="photo_finish", heal=8, gold=15, up_heal=4, up_gold=10,
         title="Photo Finish",
         lines=["Deal damage equal to your [gold]Charge[/gold].", "[gold]Sweetspot[/gold] — this kills the last enemy: heal {Heal:diff()} HP and gain {Gold:diff()} Gold."]),
]


def folder_for(rarity: str) -> str:
    return {"Basic": "Basic", "Common": "Common", "Uncommon": "Uncommon", "Rare": "Rare"}[rarity]


def gen_card(c: dict) -> str:
    name = c["name"]
    ns = folder_for(c["rarity"])
    rarity = c["rarity"]
    cost = c["cost"]
    ctype = c["card_type"]
    target = c["target"]
    tmpl = c["tmpl"]

    kw = []
    if c.get("exhaust"):
        kw.append("CardKeyword.Exhaust")
    if c.get("retain"):
        kw.append("CardKeyword.Retain")
    kw_line = f"    public override IEnumerable<CardKeyword> CanonicalKeywords => [{', '.join(kw)}];\n" if kw else ""

    gains_block = "    public override bool GainsBlock => true;\n" if tmpl in (
        "block", "rev_block", "guard_up", "stored_power", "perfect_shield"
    ) else ""

    # ---- templates ----
    if tmpl == "attack":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}{gains_block}    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new DamageVar({c['dmg']}, ValueProp.Move)];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await CommonActions.CardAttack(this, play).Execute(choiceContext);
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars.Damage.UpgradeValueBy({c.get('up_dmg', 0)}m);
    }}
}}
"""
    elif tmpl == "block":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}{gains_block}    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new BlockVar({c['block']}, ValueProp.Move)];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await CommonActions.CardBlock(this, play);
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars.Block.UpgradeValueBy({c.get('up_block', 0)}m);
    }}
}}
"""
    elif tmpl == "rev":
        up_draw = c.get("up_draw", 0)
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new CardsVar({max(up_draw, 1)})];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await Charge.Rev(choiceContext, Owner, 1, this);
        if (IsUpgraded)
            await CardPileCmd.Draw(choiceContext, DynamicVars.Cards.IntValue, Owner);
    }}

    protected override void OnUpgrade()
    {{
        // draw unlocks on upgrade; base CardsVar already set
    }}
}}
"""
    elif tmpl == "unleash":
        up_flat = c.get("up_flat", 0)
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new DynamicVar("Bonus", {up_flat})];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        var bonus = IsUpgraded ? DynamicVars["Bonus"].IntValue : 0;
        var dmg = await Charge.Unleash(choiceContext, Owner, this, reset: true, flatBonus: bonus);
        if (play.Target is not null && dmg > 0)
        {{
            await CreatureCmd.Damage(choiceContext, play.Target, dmg, ValueProp.Move, Owner.Creature, this);
        }}
    }}

    protected override void OnUpgrade()
    {{
        // +flat on Unleash via IsUpgraded check
    }}
}}
"""
    elif tmpl == "rev_block":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}{gains_block}    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new BlockVar({c['block']}, ValueProp.Move)];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await Charge.Rev(choiceContext, Owner, 1, this);
        await CommonActions.CardBlock(this, play);
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars.Block.UpgradeValueBy({c.get('up_block', 0)}m);
    }}
}}
"""
    elif tmpl == "attack_rev":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new DamageVar({c['dmg']}, ValueProp.Move)];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await CommonActions.CardAttack(this, play).Execute(choiceContext);
        await Charge.Rev(choiceContext, Owner, 1, this);
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars.Damage.UpgradeValueBy({c.get('up_dmg', 0)}m);
    }}
}}
"""
    elif tmpl == "guard_up":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}{gains_block}    protected override IEnumerable<DynamicVar> CanonicalVars =>
    [
        new BlockVar({c['block']}, ValueProp.Move),
        new BlockVar("HighBlock", {c['high_block']}, ValueProp.Move),
    ];

    protected override bool ShouldGlowGoldInternal => Charge.Get(Owner) > Charge.GetBase(Owner);

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        var above = Charge.Get(Owner) > Charge.GetBase(Owner);
        var amt = above ? DynamicVars["HighBlock"].BaseValue : DynamicVars.Block.BaseValue;
        var stored = DynamicVars.Block.BaseValue;
        DynamicVars.Block.BaseValue = amt;
        try {{ await CommonActions.CardBlock(this, play); }}
        finally {{ DynamicVars.Block.BaseValue = stored; }}
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars.Block.UpgradeValueBy({c.get('up_block', 0)}m);
        DynamicVars["HighBlock"].UpgradeValueBy({c.get('up_high', 0)}m);
    }}
}}
"""
    elif tmpl == "attack_hits_combo":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
    [
        new DamageVar({c['dmg']}, ValueProp.Move),
        new DynamicVar("Repeat", {c['hits']}),
    ];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        for (var i = 0; i < DynamicVars["Repeat"].IntValue; i++)
            await CommonActions.CardAttack(this, play).Execute(choiceContext);
        if (Charge.IsCombo(this, {c['combo']}))
            await CardPileCmd.Draw(choiceContext, 1, Owner);
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars.Damage.UpgradeValueBy({c.get('up_dmg', 0)}m);
    }}
}}
"""
    elif tmpl == "dash":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
    [
        new DamageVar({c['dmg']}, ValueProp.Move),
        new DamageVar("ComboDamage", {c['combo_dmg']}, ValueProp.Move),
    ];

    protected override bool ShouldGlowGoldInternal => Charge.IsCombo(this, {c['combo']});

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        var dmg = Charge.IsCombo(this, {c['combo']})
            ? DynamicVars["ComboDamage"].BaseValue
            : DynamicVars.Damage.BaseValue;
        var stored = DynamicVars.Damage.BaseValue;
        DynamicVars.Damage.BaseValue = dmg;
        try {{ await CommonActions.CardAttack(this, play).Execute(choiceContext); }}
        finally {{ DynamicVars.Damage.BaseValue = stored; }}
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars.Damage.UpgradeValueBy({c.get('up_dmg', 0)}m);
        DynamicVars["ComboDamage"].UpgradeValueBy({c.get('up_combo', 0)}m);
    }}
}}
"""
    elif tmpl == "attack_sweetspot_weak":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
    [
        new DamageVar({c['dmg']}, ValueProp.Move),
        new DynamicVar("Weak", {c['weak']}),
    ];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await CommonActions.CardAttack(this, play).Execute(choiceContext);
        if (play.Target is not null && Charge.IntendsToAttack(play.Target))
        {{
            await PowerCmd.Apply<WeakPower>(choiceContext, play.Target, DynamicVars["Weak"].IntValue, Owner.Creature, this);
        }}
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars.Damage.UpgradeValueBy({c.get('up_dmg', 0)}m);
    }}
}}
"""
    elif tmpl == "attack_fatal_rev":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
    [
        new DamageVar({c['dmg']}, ValueProp.Move),
        new EnergyVar({c['energy']}),
    ];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await CommonActions.CardAttack(this, play).Execute(choiceContext);
        if (play.Target is not null && play.Target.IsDead)
        {{
            await PlayerCmd.GainEnergy(DynamicVars.Energy.IntValue, Owner);
            await Charge.Rev(choiceContext, Owner, 1, this);
        }}
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars.Damage.UpgradeValueBy({c.get('up_dmg', 0)}m);
    }}
}}
"""
    elif tmpl == "weak_draw":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
    [
        new DynamicVar("Weak", {c['weak']}),
        new CardsVar({c['cards']}),
    ];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        if (play.Target is not null)
            await PowerCmd.Apply<WeakPower>(choiceContext, play.Target, DynamicVars["Weak"].IntValue, Owner.Creature, this);
        await CardPileCmd.Draw(choiceContext, DynamicVars.Cards.IntValue, Owner);
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars["Weak"].UpgradeValueBy({c.get('up_weak', 0)}m);
    }}
}}
"""
    elif tmpl == "rev_twice":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await Charge.Rev(choiceContext, Owner, 2, this);
    }}

    protected override void OnUpgrade()
    {{
        EnergyCost.UpgradeBy({c.get('up_cost', 1) - cost});
    }}
}}
"""
    elif tmpl == "redline":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new DynamicVar("Threshold", {c['threshold']})];

    protected override bool ShouldGlowGoldInternal =>
        Charge.Get(Owner) >= DynamicVars["Threshold"].IntValue;

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await Charge.Rev(choiceContext, Owner, 1, this);
        if (Charge.Get(Owner) >= DynamicVars["Threshold"].IntValue)
            await Charge.Rev(choiceContext, Owner, 1, this);
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars["Threshold"].UpgradeValueBy({c.get('up_threshold', 0)}m);
    }}
}}
"""
    elif tmpl == "power":
        amount_key = c.get("amount_key", "Amount")
        amount = c["amount"]
        up_amount = c.get("up_amount")
        up_cost = c.get("up_cost")
        energy_cards = ""
        if name == "HighlightReel":
            energy_cards = """
        new EnergyVar(2),
        new CardsVar(2),"""
            # amount is both energy and cards; power amount = 2
        vars_block = f"""
        new DynamicVar("{amount_key}", {amount}),{energy_cards}"""
        upgrade_bits = []
        if up_amount is not None:
            upgrade_bits.append(f'DynamicVars["{amount_key}"].UpgradeValueBy({up_amount}m);')
        if up_cost is not None:
            upgrade_bits.append(f"EnergyCost.UpgradeBy({up_cost - cost});")
        if not upgrade_bits:
            upgrade_bits.append("// no numeric upgrade")
        # SuperArmor / GDiffuser use amount 1 with cost upgrade
        power = c["power"]
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
    [{vars_block}
    ];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        if (Owner.Creature is null) return;
        await PowerCmd.Apply<{power}>(
            choiceContext,
            Owner.Creature,
            DynamicVars["{amount_key}"].IntValue,
            Owner.Creature,
            this);
    }}

    protected override void OnUpgrade()
    {{
        {chr(10).join('        ' + b for b in upgrade_bits)}
    }}
}}
"""
    elif tmpl == "perfect_shield":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}{gains_block}    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new BlockVar({c['block']}, ValueProp.Move)];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await CommonActions.CardBlock(this, play);
        if (Owner.Creature is not null)
        {{
            await PowerCmd.Apply<PerfectShieldTrackerPower>(
                choiceContext, Owner.Creature, 1, Owner.Creature, this);
        }}
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars.Block.UpgradeValueBy({c.get('up_block', 0)}m);
    }}
}}
"""
    elif tmpl == "pressure":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new DynamicVar("Bonus", {c.get('up_flat', 0)})];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await Charge.Ensure(choiceContext, Owner, this);
        var half = Charge.Get(Owner) / 2;
        if (IsUpgraded) half += DynamicVars["Bonus"].IntValue;
        if (play.Target is not null && half > 0)
            await CreatureCmd.Damage(choiceContext, play.Target, half, ValueProp.Move, Owner.Creature, this);
    }}

    protected override void OnUpgrade() {{ }}
}}
"""
    elif tmpl == "stored_power":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}{gains_block}    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new BlockVar(0, ValueProp.Move)];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await Charge.Ensure(choiceContext, Owner, this);
        var charge = Charge.Get(Owner);
        var block = IsUpgraded ? (charge * 2) / 3 : charge / 2;
        if (block > 0 && Owner.Creature is not null)
            await CreatureCmd.GainBlock(Owner.Creature, block, ValueProp.Move, play);
    }}

    protected override void OnUpgrade() {{ }}
}}
"""
    elif tmpl == "unleash_aoe":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new DynamicVar("Bonus", {c.get('up_flat', 0)})];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        var bonus = IsUpgraded ? DynamicVars["Bonus"].IntValue : 0;
        var dmg = await Charge.Unleash(choiceContext, Owner, this, reset: true, flatBonus: bonus);
        if (dmg > 0 && Owner.Creature?.CombatState is not null)
        {{
            await CreatureCmd.Damage(
                choiceContext,
                Owner.Creature.CombatState.HittableEnemies,
                dmg,
                ValueProp.Move,
                Owner.Creature,
                this);
        }}
    }}

    protected override void OnUpgrade() {{ }}
}}
"""
    elif tmpl == "clean_ko":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new DynamicVar("Bonus", {c.get('up_flat', 0)})];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await Charge.Ensure(choiceContext, Owner, this);
        var bonus = IsUpgraded ? DynamicVars["Bonus"].IntValue : 0;
        var dmg = Charge.Get(Owner) + bonus;
        if (play.Target is not null && dmg > 0)
        {{
            await CreatureCmd.Damage(choiceContext, play.Target, dmg, ValueProp.Move, Owner.Creature, this);
            var killed = play.Target.IsDead;
            // Always count as Unleash for Muscle Memory / YES!, but only reset if not kill
            _ = await Charge.Unleash(choiceContext, Owner, this, reset: !killed, flatBonus: 0);
            // Unleash already reset or not; but we already dealt damage manually.
            // Problem: Unleash returns damage and also does Highlight Reel — OK.
            // But Unleash also would want to deal damage — we dealt first.
            // Fix: if we Unleash after damage for tracking, we'd double-count refund only — OK.
            // Wait — Unleash resets charge; we need to NOT spend charge twice.
            // Cleaner approach below rewritten in post — see clean_ko_fixed.
        }}
    }}

    protected override void OnUpgrade() {{ }}
}}
"""
        # The above clean_ko is broken - I'll fix with a better version
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new DynamicVar("Bonus", {c.get('up_flat', 0)})];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await Charge.Ensure(choiceContext, Owner, this);
        var bonus = IsUpgraded ? DynamicVars["Bonus"].IntValue : 0;
        // Preview damage without resetting; reset only if target lives.
        var dmg = Charge.Get(Owner) + bonus;
        if (play.Target is null || dmg <= 0) return;

        await CreatureCmd.Damage(choiceContext, play.Target, dmg, ValueProp.Move, Owner.Creature, this);
        var keepCharge = play.Target.IsDead;
        // Bookkeeping: count Unleash, refund engines, optional reset
        _ = await Charge.Unleash(choiceContext, Owner, this, reset: !keepCharge, flatBonus: 0);
        // Unleash re-reads Charge for return value but we already dealt — if reset:false Charge stays.
        // If keepCharge is false, Unleash resets (good). If true, Charge was still full when Unleash ran...
        // BUG: Unleash doesn't spend when reset:false, good. But when reset:true it sets to base — good.
        // When keepCharge, Charge still full — Unleash still increments unleash count and Highlight Reel — good.
    }}

    protected override void OnUpgrade() {{ }}
}}
"""
    elif tmpl == "knee":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
    [
        new DamageVar({c['dmg']}, ValueProp.Move),
        new DamageVar("SweetDamage", {c['sweet']}, ValueProp.Move),
    ];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        var sweet = play.Target is not null && Charge.IntendsToAttack(play.Target);
        var dmg = sweet ? DynamicVars["SweetDamage"].BaseValue : DynamicVars.Damage.BaseValue;
        var stored = DynamicVars.Damage.BaseValue;
        DynamicVars.Damage.BaseValue = dmg;
        try {{ await CommonActions.CardAttack(this, play).Execute(choiceContext); }}
        finally {{ DynamicVars.Damage.BaseValue = stored; }}
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars.Damage.UpgradeValueBy({c.get('up_dmg', 0)}m);
        DynamicVars["SweetDamage"].UpgradeValueBy({c.get('up_sweet', 0)}m);
    }}
}}
"""
    elif tmpl == "grab":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new DamageVar({c['dmg']}, ValueProp.Move)];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        if (play.Target is not null && play.Target.Block > 0)
            await CreatureCmd.LoseBlock(play.Target, play.Target.Block);
        await CommonActions.CardAttack(this, play).Execute(choiceContext);
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars.Damage.UpgradeValueBy({c.get('up_dmg', 0)}m);
    }}
}}
"""
    elif tmpl == "spot_dodge":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        if (Owner.Creature is null) return;
        // Buffer = next attack(s) deal 0 HP loss
        await PowerCmd.Apply<BufferPower>(choiceContext, Owner.Creature, 1, Owner.Creature, this);
    }}

    protected override void OnUpgrade()
    {{
        EnergyCost.UpgradeBy({c.get('up_cost', 0) - cost});
    }}
}}
"""
    elif tmpl == "yes":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
    [
        new EnergyVar({c['energy']}),
        new CardsVar({c['cards']}),
    ];

    protected override bool ShouldGlowGoldInternal => Charge.DidUnleashThisTurn(Owner);

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        if (!Charge.DidUnleashThisTurn(Owner)) return;
        await PlayerCmd.GainEnergy(DynamicVars.Energy.IntValue, Owner);
        await CardPileCmd.Draw(choiceContext, DynamicVars.Cards.IntValue, Owner);
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars.Energy.UpgradeValueBy({c.get('up_energy', 0)}m);
    }}
}}
"""
    elif tmpl == "warmup":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
    [
        new CardsVar({c['cards']}),
        new EnergyVar({c['energy']}),
    ];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await CardPileCmd.Draw(choiceContext, DynamicVars.Cards.IntValue, Owner);
        if (Charge.IsCombo(this, {c['combo']}))
            await PlayerCmd.GainEnergy(DynamicVars.Energy.IntValue, Owner);
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars.Cards.UpgradeValueBy({c.get('up_cards', 0)}m);
    }}
}}
"""
    elif tmpl == "falcon_punch":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        var dmg = await Charge.Unleash(choiceContext, Owner, this, reset: true, multiplier: 2m);
        if (play.Target is null || dmg <= 0 || Owner.Creature is null) return;

        var results = await CreatureCmd.Damage(
            choiceContext, play.Target, dmg, ValueProp.Move, Owner.Creature, this);
        // Follow-Through: overkill hits another enemy
        var overkill = results.Sum(r => r.OverkillDamage);
        if (overkill > 0 && Owner.Creature.CombatState is not null)
        {{
            var next = Owner.Creature.CombatState.HittableEnemies
                .FirstOrDefault(e => e != play.Target && e.IsAlive);
            if (next is not null)
                await CreatureCmd.Damage(choiceContext, next, overkill, ValueProp.Move, Owner.Creature, this);
        }}
    }}

    protected override void OnUpgrade()
    {{
        EnergyCost.UpgradeBy({c.get('up_cost', 2) - cost});
    }}
}}
"""
    elif tmpl == "blue_falcon":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await Charge.Ensure(choiceContext, Owner, this);
        var dmg = Charge.Get(Owner);
        if (dmg > 0 && Owner.Creature?.CombatState is not null)
        {{
            await CreatureCmd.Damage(
                choiceContext,
                Owner.Creature.CombatState.HittableEnemies,
                dmg,
                ValueProp.Move,
                Owner.Creature,
                this);
        }}
    }}

    protected override void OnUpgrade()
    {{
        EnergyCost.UpgradeBy({c.get('up_cost', 2) - cost});
    }}
}}
"""
    elif tmpl == "muscle_memory":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        var times = 1 + Charge.UnleashCount(Owner);
        await Charge.Rev(choiceContext, Owner, times, this);
    }}

    protected override void OnUpgrade()
    {{
        EnergyCost.UpgradeBy({c.get('up_cost', 0) - cost});
    }}
}}
"""
    elif tmpl == "hard_read":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
        [new EnergyVar(1)];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        if (play.Target is not null && Charge.IntendsToAttack(play.Target))
        {{
            await CreatureCmd.Stun(play.Target, "");
            if (IsUpgraded)
                await PlayerCmd.GainEnergy(DynamicVars.Energy.IntValue, Owner);
        }}
        else
        {{
            await CardPileCmd.Draw(choiceContext, 1, Owner);
        }}
    }}

    protected override void OnUpgrade() {{ }}
}}
"""
    elif tmpl == "photo_finish":
        body = f"""public sealed class {name}() : BlakeCard({cost}, CardType.{ctype}, CardRarity.{rarity}, TargetType.{target})
{{
{kw_line}    protected override IEnumerable<DynamicVar> CanonicalVars =>
    [
        new HealVar({c['heal']}),
        new GoldVar({c['gold']}),
    ];

    protected override async Task OnPlay(PlayerChoiceContext choiceContext, CardPlay play)
    {{
        await Charge.Ensure(choiceContext, Owner, this);
        var dmg = Charge.Get(Owner);
        // Spend the punch (reset Charge)
        _ = await Charge.Unleash(choiceContext, Owner, this, reset: true);
        if (play.Target is not null && dmg > 0)
            await CreatureCmd.Damage(choiceContext, play.Target, dmg, ValueProp.Move, Owner.Creature, this);

        // Sweetspot: last enemy dead after this
        var combat = Owner.Creature?.CombatState;
        if (combat is not null && !combat.HittableEnemies.Any(e => e.IsAlive))
        {{
            if (Owner.Creature is not null)
                await CreatureCmd.Heal(Owner.Creature, DynamicVars.Heal.IntValue);
            await PlayerCmd.GainGold(DynamicVars.Gold.IntValue, Owner);
        }}
    }}

    protected override void OnUpgrade()
    {{
        DynamicVars.Heal.UpgradeValueBy({c.get('up_heal', 0)}m);
        DynamicVars.Gold.UpgradeValueBy({c.get('up_gold', 0)}m);
    }}
}}
"""
    else:
        raise ValueError(f"Unknown tmpl {tmpl} for {name}")

    return HEADER.format(ns=ns) + "\n" + body


def loc_key(name: str) -> str:
    # BLAKE-FALCON_PUNCH from FalconPunch
    import re
    snake = re.sub(r'(?<!^)(?=[A-Z])', '_', name).upper()
    return f"BLAKE-{snake}"


def write_loc(kit: list[dict]) -> None:
    data = {}
    for c in kit:
        key = loc_key(c["name"])
        data[f"{key}.title"] = c["title"]
        # Use base lines; upgrades that change wording still work via DynamicVars
        lines = c.get("lines", [])
        data[f"{key}.description"] = "\n".join(lines)
    LOC.parent.mkdir(parents=True, exist_ok=True)
    LOC.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {LOC} ({len(kit)} cards)")


def write_docs(kit: list[dict]) -> None:
    docs = []
    for c in kit:
        docs.append({
            "id": c["name"],
            "title": c["title"],
            "rarity": c["rarity"],
            "cost": c["cost"],
            "type": c["card_type"],
            "text": " ".join(c.get("lines", [])),
            "role": c.get("role", ""),
        })
    DOCS.parent.mkdir(parents=True, exist_ok=True)
    DOCS.write_text(json.dumps(docs, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {DOCS}")


def ensure_portraits(kit: list[dict]) -> None:
    fallback = PORTRAITS / "card.png"
    big_fallback = PORTRAITS_BIG / "card.png"
    if not fallback.exists():
        print("No card.png fallback — skip portrait stubs")
        return
    for c in kit:
        stem = c["name"].lower()
        dst = PORTRAITS / f"{stem}.png"
        dst_big = PORTRAITS_BIG / f"{stem}.png"
        if not dst.exists():
            dst.write_bytes(fallback.read_bytes())
        if big_fallback.exists() and not dst_big.exists():
            dst_big.write_bytes(big_fallback.read_bytes())


def main() -> None:
    counts = {"Basic": 0, "Common": 0, "Uncommon": 0, "Rare": 0}
    for c in KIT:
        ns = folder_for(c["rarity"])
        out = CODE / ns / f"{c['name']}.cs"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(gen_card(c), encoding="utf-8")
        counts[c["rarity"]] += 1
        print(f"  {ns}/{c['name']}.cs")

    write_loc(KIT)
    write_docs(KIT)
    ensure_portraits(KIT)
    print("Counts:", counts)
    print("Done.")


if __name__ == "__main__":
    main()
